// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl =
  process.env["DATABASE_URL"] ||
  process.env["product_POSTGRES_PRISMA_URL"] ||
  process.env["POSTGRES_PRISMA_URL"] ||
  process.env["product_DATABASE_URL"] ||
  "postgresql://user:password@localhost:5432/expert_recruiter?schema=public";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
